#url: https://openplanetary.github.io/opm/exolss
baseurl: ''

# Site settings
title: Where On Mars?
email: nmanaud@gmail.com
description: "Interactive web map visualization of the ESA's ExoMars Rover candidates landing sites"

# Color settings (hex-codes without the leading hash-tag) fed136, fec503
color:
  # primary: fec503
  # secondary: fed136


  primary: EFAF3D
  secondary: D14D3C #E49929 #D14D3C

  secondary-dark: 341a13

# Team names, titles and social links
people:
- name: Nicolas Manaud
  pic: 1
  position: ESAC Trainee Project Lead
  social:
    - title: twitter
      url: https://twitter.com/nmanaud
    - title: github
      url:  https://github.com/nmanaud

- name: Oriol Boix
  pic: 2
  position: Geospatial Data & Front-End Developer
  social:
    - title: twitter
      url: https://twitter.com/oriolbx
    - title: github
      url:  https://github.com/oriolbx

- name: Carla Iriberri
  pic: 3
  position: CartoDB Support
  social:
    - title: twitter
      url: https://twitter.com/iriberri1
    - title: github
      url: https://github.com/iriberri

- name: Andrew Hill
  pic: 4
  position: Project Co-supervisor
  social:
    - title: twitter
      url: https://twitter.com/andrewxhill
    - title: github
      url: https://github.com/andrewxhill

# - name: Carla Iriberri
#   pic: 5
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/opmteam
#  - title: facebook
#    url: https://www.facebook.com/whereonmars
  - title: github
    url: https://github.com/openplanetary/opm

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-65388785-1'
